[package]
name = "project-grades"
version = "0.2.0"
authors = ["Vinnie Caprarola <vinnie@vcaprarola.me>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
chrono = "0.4"
clap = { version = "2.33", features = ["yaml"] }
